/** Display names for all doc topic lang slugs */
export const LANG_NAMES: Record<string, string> = {
  python: "Python",
  javascript: "JavaScript",
  typescript: "TypeScript",
  react: "React",
  "html-css": "HTML & CSS",
  java: "Java",
  sql: "SQL",
  go: "Go",
  rust: "Rust",
  c: "C",
  cpp: "C++",
  csharp: "C#",
  php: "PHP",
  nodejs: "Node.js",
  langchain: "LangChain",
  kotlin: "Kotlin",
  ruby: "Ruby",
  swift: "Swift",
  // AI ecosystem topics
  "ai-models": "AI Models",
  "prompt-engineering": "Prompt Engineering",
  "claude-code": "Claude Code",
  "ai-coding-tools": "AI Coding Tools",
  plugins: "Plugins & Extensions",
  mcp: "MCPs",
  "ai-cli": "CLI & Automation",
};
